include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "lib/src/core/localization/gen/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    - avoid_dynamic_calls
    - avoid_print
    - prefer_single_quotes
    - annotate_overrides
    - file_names
    - lines_longer_than_80_chars
    - require_trailing_commas
    - use_named_constants
    - combinators_ordering
    - use_key_in_widget_constructors

    # - prefer_relative_imports
