name: yandex_todo_list
description: "A new Flutter project."

publish_to: "none"


version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  uuid: ^4.4.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.2

  stream_transform: ^2.1.0
  rxdart: ^0.27.7



  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  image_path_android: "assets/images/icon1024.png"
  image_path_ios: "assets/images/icon1024.png"
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
